[package]
name = "odysseus-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
odysseus-solver-macros = { path = "../odysseus-solver-macros" }
nalgebra = "0.32"
num-traits = "0.2"
sprs = "0.11"
sprs-ldl = "0.10"
rerun = { version = "0.32", optional = true }
rand = "0.10"
rand_chacha = "0.10"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
approx = "0.5"

[features]
default = []
visualization = ["rerun"]
